name: Test action
description: Test action for dotnet application

runs:
  using: 'composite'       
  steps:
  
    - name: Restore dependencies
      run: dotnet restore
      shell: bash
      
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
      shell: bash
      
    - name: test with dotnet
      run: dotnet test --no-build --verbosity normal
      shell: bash
