name: Run action
description: run action for dotnet application

inputs:
   FILENAME:
      required: true
      type: string

runs:
  using: 'composite'       
  steps:
    - name: run with dotnet
      run: dotnet run --project ${{inputs.FILENAME}}  # eg:- filename.csproj
      shell: bash
