name: 'setupdotnet'
description: 'settingup dotnet'
runs:
 using: 'composite'
 steps:
   - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Adjust based on your .NET version