name: .NET with reusable actions

on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: MohithPilli/reusable-demo-workflows/.github/actions/checkout@master  

    - name: terraform
      uses: MohithPilli/reusable-demo-workflows/.github/actions/terraform@master
    
    - name: securityscan
      uses: MohithPilli/reusable-demo-workflows/.github/actions/SecurityScan@master

    - name: Setup .NET Core
      uses: MohithPilli/reusable-demo-workflows/.github/actions/SetUpDotNet@master

    - name: Restore dependencies
      uses: MohithPilli/reusable-demo-workflows/.github/actions/restore dependencies@master

    - name: Build
      uses: MohithPilli/reusable-demo-workflows/.github/actions/build@master

    - name: test
      uses: MohithPilli/reusable-demo-workflows/.github/actions/test@master

    - name: package
      uses: MohithPilli/reusable-demo-workflows/.github/actions/package@master

    - name: publish artifacts
      uses: MohithPilli/reusable-demo-workflows/.github/actions/Publish@master
   
    - name: deploy
      uses: MohithPilli/reusable-demo-workflows/.github/actions/Deploy@master